version: "3.8"

services:
  postgresql:
    container_name: container_name
    image: docker.io/bitnami/postgresql:latest
    environment:
      - POSTGRESQL_ROOT_USER=${POSTGRESQL_ROOT_USER}
      - POSTGRESQL_ROOT_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}

    ports:
      - "5432:5432"
    volumes:
      - "./pg_docker/postgresql_data:/bitnami/postgresql"
    restart: always


volumes:
  postgresql_data:
    driver: local