# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:4.1
    ports:
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_ERL_COOKIE=${RABBITMQ_ERL_COOKIE}

    volumes:
      - ./rabbitmq_data:/bitnami/rabbitmq/mnesia
volumes:
  rabbitmq_data:
    driver: local